//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolocation_Portal_Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<file_search_tag> file_search_tag { get; set; }
        public virtual DbSet<licence> licence { get; set; }
        public virtual DbSet<publisher> publisher { get; set; }
        public virtual DbSet<record> record { get; set; }
        public virtual DbSet<record_comment> record_comment { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<search_tag> search_tag { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
