//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolocation_Portal_Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<licence> licence { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<publisher> publisher { get; set; }
        public virtual DbSet<record> record { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<searchtag> searchtag { get; set; }
        public virtual DbSet<user> user { get; set; }

        public file file1
        {
            get => default;
            set
            {
            }
        }

        public category category1
        {
            get => default;
            set
            {
            }
        }

        public record record1
        {
            get => default;
            set
            {
            }
        }

        public licence licence1
        {
            get => default;
            set
            {
            }
        }

        public role role1
        {
            get => default;
            set
            {
            }
        }

        public publisher publisher1
        {
            get => default;
            set
            {
            }
        }

        public location location1
        {
            get => default;
            set
            {
            }
        }

        public user user1
        {
            get => default;
            set
            {
            }
        }

        public searchtag searchtag1
        {
            get => default;
            set
            {
            }
        }

        public comment comment1
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.filesController filesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.categoriesController categoriesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.locationsController locationsController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.commentsController commentsController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.usersController usersController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.publishersController publishersController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.licencesController licencesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.API.recordsController recordsController
        {
            get => default;
            set
            {
            }
        }
    }
}
