//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolocation_Portal_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public record()
        {
            this.file = new HashSet<file>();
        }
    
        public int Id { get; set; }
        public System.DateTime dataset_upload { get; set; }
        public System.DateTime dataset_modified_date { get; set; }

        [Required(ErrorMessage = "Bitte geben Sie einen Titel an.")]
        [StringLength(160)]
        [DisplayName("Titel")]
        public string title { get; set; }

        [StringLength(3000)]
        [DisplayName("Beschreibung")]
        public string description { get; set; }

        [DisplayName("Kategorie")]
        public Nullable<int> category_id { get; set; }

        [DisplayName("Lizenz")]
        public Nullable<int> licence_id { get; set; }

        [DisplayName("Publisher")]
        public Nullable<int> publisher_id { get; set; }

        public Nullable<int> rating { get; set; }

        [DisplayName("Sichtbarkeit")]
        public Nullable<int> role_id { get; set; }

        [DisplayName("Anzeigen?")]
        public bool record_active { get; set; }

        [DisplayName("Örtlichkeit")]
        public int location_id { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> file { get; set; }
        public virtual publisher publisher { get; set; }
        public virtual comment comment { get; set; }
        public virtual licence licence { get; set; }
        public virtual location location { get; set; }
    }
}
