//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolocation_Portal_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int Id { get; set; }
        public System.DateTime dataset_upload { get; set; }
        public System.DateTime dataset_modified_date { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> licence_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> role_id { get; set; }
        public bool record_active { get; set; }
    }
}
